export enum AtendimentoSaude {
    CONSULTA_COM_TECNICO_NO_POSTO_DE_SAUDE_DA_COMUNIDADE = 'CONSULTA_COM_TECNICO_NO_POSTO_DE_SAUDE_DA_COMUNIDADE',
    CONSULTA_COM_O_ENFERMEIRO_NO_POSTO_DE_SAUDE = 'CONSULTA_COM_O_ENFERMEIRO_NO_POSTO_DE_SAUDE',
    ATENDIMENTO_NO_PROGRAMA_SAUDE_DA_FAMILIA = 'ATENDIMENTO_NO_PROGRAMA_SAUDE_DA_FAMILIA',
    ATENDIMENTO_POR_AGENTES_COMUNITARIOS_DE_SAUDE = 'ATENDIMENTO_POR_AGENTES_COMUNITARIOS_DE_SAUDE',
    TRATA_COM_CURANDEIRO = 'TRATA_COM_CURANDEIRO',
    PARTICIPA_DAS_CAMPANHAS_DE_VACINACAO = 'PARTICIPA_DAS_CAMPANHAS_DE_VACINACAO',
    ATENDIMENTO_POR_PARTEIRAS = 'ATENDIMENTO_POR_PARTEIRAS',
    ATENDIMENTO_EM_OUTRA_LOCALIDADE = 'ATENDIMENTO_EM_OUTRA_LOCALIDADE',
    NAO_DECLARADO = 'NAO_DECLARADO',
    OUTROS = 'OUTROS'
}
