export enum AtividadesProdutivas {
    PESCA_ARTESANAL = "PESCA_ARTESANAL",
    COMERCIO = "COMÉRCIO",
    SERVICO = "SERVIÇO",
    INDUSTRIA_E_COMERCIO = "INDÚSTRIA_E_COMÉRCIO",
    SERVICO_E_COMERCIO = "SERVIÇO_E_COMÉRCIO",
    NENHUMA = "NENHUMA"
}
