export enum DestinoPescado {
    CONSUMIDOR_DIRETO,
	ATRAVESSADOR,
	ENTREPOSTO,
	OUTROS_PESCADORES,
	SUPERMERCADOS,
	POSTO_DE_COMBUSTIVEL,
	COLONIA,
	ASSOCIACAO,
	COOPERATIVA,
	FEIRA,
	OUTROS,
	NAO_DECLARADO
}