export enum DestinoPescado {
    CONSUMIDOR_DIRETO = 'CONSUMIDOR_DIRETO',
    ATRAVESSADOR = 'ATRAVESSADOR',
    ENTREPOSTO = 'ENTREPOSTO',
    OUTROS_PESCADORES = 'OUTROS_PESCADORES',
    SUPERMERCADOS = 'SUPERMERCADOS',
    POSTO_DE_COMBUSTIVEL = 'POSTO_DE_COMBUSTIVEL',
    COLONIA = 'COLONIA',
    ASSOCIACAO = 'ASSOCIACAO',
    COOPERATIVA = 'COOPERATIVA',
    FEIRA = 'FEIRA',
    OUTROS = 'OUTROS',
    NAO_DECLARADO = 'NAO_DECLARADO'
}
