export enum documentacao {
    RECIBO_DE_COMPRA_E_VENDA = 'RECIBO_DE_COMPRA_E_VENDA',
    ESCRITURA_PUBLICA = 'ESCRITURA_PUBLICA',
    ESCRITUA = 'ESCRITUA',
    CERTIDAO = 'CERTIDAO',  
    TITULO_DE_POSSE = 'TÍTULO_DE_POSSE',  
    NAO_POSSUI = 'NAO_POSSUI'  
}
