export enum documentacao {
    RECIBO_DE_COMPRA_E_VENDA = 'RECIBO_DE_COMPRA_E_VENDA',
    ESCRITURA_PUBLICA = 'ESCRITURA_PUBLICA',
    ESCRITUA = 'ESCRITUA',
    CERTIDAO = 'CERTIDÃO',  
    TITULO_DE_POSSE = 'TÍTULO_DE_POSSE',  
    NAO_POSSUI = 'NÃO_POSSUI'
}
