export enum Escolaridade {
    NENHUM = 'NENHUM',
    FUNDAMENTAL_COMPLETO = 'FUNDAMENTAL_COMPLETO',
    FUNDAMENTAL_INCOMPLETO = 'FUNDAMENTAL_INCOMPLETO',
    MÉDIO_COMPLETO = 'MÉDIO_COMPLETO',
    MÉDIO_INCOMPLETO = 'MÉDIO_INCOMPLETO',
    SUPERIOR_COMPLETO = 'SUPERIOR_COMPLETO',
    SUPERIOR_INCOMPLETO = 'SUPERIOR_INCOMPLETO',
    PÓS_GRADUAÇÃO = 'PÓS_GRADUAÇÃO'
}
