export enum Escolaridade {
    ANALFABETO = 'ANALFABETO',
    FUNDAMENTAL_COMPLETO = 'FUNDAMENTAL_COMPLETO',
    FUNDAMENTAL_INCOMPLETO = 'FUNDAMENTAL_INCOMPLETO',
    MÉDIO_COMPLETO = 'ENSINO_MÉDIO_COMPLETO',
    MÉDIO_INCOMPLETO = 'ENSINO_MÉDIO_INCOMPLETO',
    SUPERIOR_COMPLETO = 'ENSINO_SUPERIOR_COMPLETO',
    SUPERIOR_INCOMPLETO = 'ENSINO_SUPERIOR_INCOMPLETO',
    PÓS_GRADUAÇÃO = 'PÓS_GRADUAÇÃO'
}
