export enum esporteLazerEnum {
    CAMPO_DE_FUTEBOL = 'CAMPO_DE_FUTEBOL',
    QUADRA_POLIESPORTIVA = 'QUADRA_POLIESPORTIVA',
    SEDE_ESPORTIVA = 'SEDE_ESPORTIVA',
    BALNEARIOS = 'BALNEÁRIOS',
    PARQUES = 'PARQUES',
    OUTROS = 'OUTROS'
}
