export enum FontesRenda {
    EMPREGADO_FIXO_COM_CARTEIRA_ASSINADA = "EMPREGADO_FIXO_COM_CARTEIRA_ASSINADA",
    EMPREGADO_FIXO_SEM_CARTEIRA_ASSINADA = "EMPREGADO_FIXO_SEM_CARTEIRA_ASSINADA",
    SERVIDOR_PUBLICO = "SERVIDOR_PÚBLICO",
    TRABALHO_INFORMAL = "TRABALHO_INFORMAL",
    BOLSA_FAMILIA = "BOLSA_FAMÍLIA",
    BPC = "BPC",
    APOSENTADORIA = "APOSENTADORIA",
    APOSENTADORIA_RURAL = "APOSENTADORIA_RURAL",
    PENSAO_TEMPORARIA = "PENSÃO_TEMPORÁRIA",
    PENSAO_PERMANENTE = "PENSÃO_PERMANENTE",
    SEGURO_DESEMPREGO = "SEGURO_DESEMPREGO",
    RENDA_LOCACAO_DE_BENS = "RENDA_LOCAÇÃO_DE_BENS",
    OUTROS = "OUTROS"
}
