// Instituicao.ts
export enum Instituicao {
    SINDICATO = "SINDICATO",
    COLONIA_DE_PESCA = "COLONIA_DE_PESCA",
    ASSOCIACAO = "ASSOCIACAO",
    CONSELHO = "CONSELHO",
    PARTIDO_POLITICO = "PARTIDO_POLITICO",
    IGREJA = "IGREJA",
    NAO_DECLARADO = "NAO_DECLARADO",
    OUTRO = "OUTRO"
}
