export enum MetodoTratamentoAgua {
    FERVURA = "FERVURA",
    FILTRACAO = "FILTRACAO",
    CLORACAO = "CLORACAO",
    OSMOSE_REVERSA = "OSMOSE_REVERSA",
    DESTILACAO = "DESTILACAO",
    ULTRAVIOLETA = "ULTRAVIOLETA",
    OUTROS = "OUTROS"
}
