// Molestias.ts
export enum Molestias {
    DESCONHECE = "DESCONHECE",
    MALARIA = "MALÁRIA",
    LEISHMANIOSE = "LEISHMANIOSE",
    HEPATITE = "HEPATITE",
    DENGUE = "DENGUE",
    DIARREIA = "DIARRÉIA",
    LEPTOSPIROSE = "LEPTOSPIROSE",
    DOENCA_RESPIRATORIA = "DOENÇA_RESPIRATÓRIA",
    MORDIDA_DE_MORCEGO = "MORDIDA_DE_MORCEGO",
    TUBERCULOSE = "TUBERCULOSE",
    DST = "DST",
    CANCER = "CANCER",
    DESNUTRICAO = "DESNUTRIÇÃO",
    COVID_19 = "COVID_19",
    OUTRA = "OUTRA"
}
