export enum Ocorrencia {

	NUNCA = 'NUNCA',
	FREQUENTEMENTE = 'FREQUENTEMENTE', 
	NO_PERIODO_DE_CUVAS = 'NO_PERIODO_DE_CUVAS',
	RARAMENTE = 'RARAMENTE',
	DEIXOU_DE_OCORRER = 'DEIXOU_DE_OCORRER',
	NAO_INFORMADO = 'NAO_INFORMADO',
	
}
