export enum origemMaterialConstrucao {
	LOJA_DA_CIDADE = 'LOJA_DA_CIDADE',
	EXTRACAO_EM_LOCAL_DISTANTE_ACIMA_DE_5KM = 'EXTRACAO_EM_LOCAL_DISTANTE_ACIMA_DE_5KM',
	ESTACAO_PROXIMA = 'ESTACAO_PROXIMA',
	EXTRACAO_EM_AREA_OBJETO_UC = 'EXTRACAO_EM_AREA_OBJETO_UC',
	NAO_SE_APLICA = 'NAO_SE_APLICA',
	NAO_DECALARADO = 'NAO_DECALARADO', 
	OUTRO = 'OUTRO',
}

