export enum PescariaCusteio {
    RANCHO = 'RANCHO',
    APETRECHO = 'APETRECHO',
    EMBARCACAO = 'EMBARCACAO',
    COMBUSTIVEL = 'COMBUSTIVEL',
    GELO = 'GELO',
    ISOPOR = 'ISOPOR',
    OUTRO = 'OUTRO',
    NAO_DECLARADO = 'NAO_DECLARADO',
    NAO_SE_APLICA = 'NAO_SE_APLICA'
}
