export enum Servico {
    TELEFONE_PUBLICO = 'TELEFONE_PUBLICO',
    DELEGACIA = 'DELEGACIA',
    RESTAURANTE = 'RESTAURANTE',
    MERCADO = 'MERCADO',
    IGREJA = 'IGREJA',
    NAO_DECLARADO = 'NAO_DECLARADO',
    NENHUM = 'NENHUM'
}
