export enum ServicosBasicos {
    TELEFONE_PUBLICO = "TELEFONE_PUBLICO",
    PARADAS_ONIBUS = "PARADAS_ONIBUS",
    CORREIOS = "CORREIOS",
    FARMACIAS = "FARMACIAS",
    BANCOS = "BANCOS",
    ESCOLAS = "ESCOLAS",
    POSTO_SAUDE_HOSPITAL = "POSTO_SAUDE_HOSPITAL",
    DELEGACIA = "DELEGACIA",
    CEMITERIO = "CEMITERIO",
    IGREJAS = "IGREJAS",
    SUPERMERCADOS = "SUPERMERCADOS",
    HOTEL_POUSADA = "HOTEL_POUSADA",
    RESTAURANTE = "RESTAURANTE",
    FUNERARIA = "FUNERARIA"
}
