export enum TipoBarco {
    CASQUINHO = 'CASQUINHO',
    CANOA = 'CANOA',
    RABETA = 'RABETA',
    VOADEIRA = 'VOADEIRA',
    BARCO_COM_MOTOR_DE_CENTRO = 'BARCO_COM_MOTOR_DE_CENTRO',
    GELEIRA = 'GELEIRA',
    OUTRO = 'OUTRO',
    NAO_INFORMADO = 'NAO_INFORMADO'
}
