export enum ViolenciaTipo {
    ASSALTO = 'ASSALTO',
    CONFLITO_FUNDIÁRIO = 'CONFLITO_FUNDIÁRIO',
    ESTUPRO = 'ESTUPRO',
    AMEAÇA_DE_MORTE = 'AMEAÇA_DE_MORTE',
    AGRESSÃO_FÍSICA = 'AGRESSÃO_FÍSICA',
    AGRESSÃO_MORAL = 'AGRESSÃO_MORAL',
    AGRESSÃO_PSICOLÓLICA = 'AGRESSÃO_PSICOLÓLICA'
}
