export enum Vizinhos {
    LADO_ESQUERDO_LADO_DIREITO_ATRAS = 'LADO_ESQUERDO_LADO_DIREITO_ATRAS',
    LADO_ESQUERDO_LADO_DIREITO = 'LADO_ESQUERDO_LADO_DIREITO',
    LADO_ESQUERDO_ATRAS = 'LADO_ESQUERDO_ATRAS',
    LADO_ESQUERDO_APENAS = 'LADO_ESQUERDO_APENAS',
    LADO_DIREITO_ATRAS = 'LADO_DIREITO_ATRAS',
    LADO_DIREITO_APENAS = 'LADO_DIREITO_APENAS',
    ATRAS_SOMENTE = 'ATRAS_SOMENTE',
    NAO_DECLARADO = 'NAO_DECLARADO',
    NAO_POSSUI = 'NAO_POSSUI'
}
