export const EntrevistadoSchema = {
  name: 'Entrevistado',
  primaryKey: 'id',
  properties: {
      id: 'int',
      nome: 'string',
      naturalidade: 'string',
      nascimentoData: 'date',
      sexo: 'string',
      apelido: 'string',
      escolaridade: 'string',
      estadoCivil: 'string',
      religiao: 'string',
      morador: 'string',
      dataChegada: 'date',
      pretendeMudar: 'string',
      motivoVontadeMudanca: 'string',
      relacaoAreaImovel: 'string?',
      relacaoVizinhos: 'string?',
      tipoAlimentacao: 'string?',
      localCompras: 'string?',
      servicosDeficitarios: 'string?',
      sofreuAssaltos: 'int',
      presenciouAssalto: 'int',
      problemasDeViolenciaLocal: 'string?',
      conheceUcs: 'string',
      conheceUcProposta: 'string',
      conheceAreaUc: 'string?',
      utilizaAreaUc: 'string?',
      propostaMelhorarArea: 'string',
      indicadoConsultaPublica: 'string',
      contatoIndicadoConsultaPublica: 'string',
      localidade: 'int?',
      sincronizado: 'bool?',
      idLocal: 'string?'
  }
};
