
export const estadoCivilOptions = [
    'Casado(a)',
    'Solteiro(a)',
    'União estável',
    'Viúvo(a)',
    'Separado(a)'
  ];

export const tempomoradiaOptions = [
      'Entre 1 e 5 anos',
      'Entre 6 e 10 anos',
      'Entre 11 e 15 anos',
      'Entre 16 e  20 anos',
      'Entre 21 e 25 anos',
      'Entre 26 e 30 anos',
      'Acima de 30 anos'];
      
 export const saudeOptions =[
        'Consulta com técnico no posto de saúde da comunidade',
        'Consulta com o enfermeiro no posto de saúde',
        'Atendimento no Programa Saúde da Família',
        'Atendimento por agentes comunitários de saúde',
        'Trata com curandeiro',
        'Participa das campanhas de vacinação',
        'Atendimento por parteiras',
        'Atendimento em outra localidade',
        'Não declarado',
        'Outros'
      ];
  export const Escolaridade = [
        "Analfabeto",
        "Fundamental completo",
        "Fundamental incompleto",
        "Ensino médio completo",
        "Ensino médio incompleto",
        "Ensino superior completo",
        "Ensino superior incompleto",
        "Pós-graduação"
      ];

  export const Naturalidade = [
  'Em outro estado',
  'Em outro país',
  'Abaetetuba',
  'Abel Figueiredo',
  'Acará',
  'Afuá',
  'Água Azul do Norte',
  'Alenquer',
  'Almeirim',
  'Altamira',
  'Anajás',
  'Ananindeua',
  'Anapu',
  'Augusto Corrêa',
  'Aurora do Pará',
  'Aveiro',
  'Bagre',
  'Baião',
  'Bannach',
  'Barcarena',
  'Belém',
  'Belterra',
  'Benevides',
  'Bom Jesus do Tocantins',
  'Bonito',
  'Bragança',
  'Brasil Novo',
  'Brejo Grande do Araguaia',
  'Breu Branco',
  'Breves',
  'Bujaru',
  'Cachoeira do Arari',
  'Cachoeira do Piriá',
  'Cametá',
  'Canaã dos Carajás',
  'Capanema',
  'Capitão Poço',
  'Castanhal',
  'Chaves',
  'Colares',
  'Conceição do Araguaia',
  'Concórdia do Pará',
  'Cumaru do Norte',
  'Curionópolis',
  'Curralinho',
  'Curuá',
  'Curuçá',
  'Dom Eliseu',
  'Eldorado do Carajás',
  'Faro',
  'Floresta do Araguaia',
  'Garrafão do Norte',
  'Goianésia do Pará',
  'Gurupá',
  'Igarapé-Açu',
  'Igarapé-Miri',
  'Inhangapi',
  'Ipixuna do Pará',
  'Irituia',
  'Itaituba',
  'Itupiranga',
  'Jacareacanga',
  'Jacundá',
  'Juruti',
  'Limoeiro do Ajuru',
  'Mãe do Rio',
  'Magalhães Barata',
  'Marabá',
  'Maracanã',
  'Marapanim',
  'Marituba',
  'Medicilândia',
  'Melgaço',
  'Mocajuba',
  'Moju',
  'Mojuí dos Campos',
  'Monte Alegre',
  'Muaná',
  'Nova Esperança do Piriá',
  'Nova Ipixuna',
  'Nova Timboteua',
  'Novo Progresso',
  'Novo Repartimento',
  'Óbidos',
  'Oeiras do Pará',
  'Oriximiná',
  'Ourém',
  'Ourilândia do Norte',
  'Pacajá',
  'Palestina do Pará',
  'Paragominas',
  'Parauapebas',
  "Pau D'Arco",
  'Peixe-Boi',
  'Piçarra',
  'Placas',
  'Ponta de Pedras',
  'Portel',
  'Porto de Moz',
  'Prainha',
  'Primavera',
  'Quatipuru',
  'Redenção',
  'Rio Maria',
  'Rondon do Pará',
  'Rurópolis',
  'Salinópolis',
  'Salvaterra',
  'Santa Bárbara do Pará',
  'Santa Cruz do Arari',
  'Santa Izabel do Pará',
  'Santa Luzia do Pará',
  'Santa Maria das Barreiras',
  'Santa Maria do Pará',
  'Santana do Araguaia',
  'Santarém',
  'Santarém Novo',
  'Santo Antônio do Tauá',
  'São Caetano de Odivelas',
  'São Domingos do Araguaia',
  'São Domingos do Capim',
  'São Félix do Xingu',
  'São Francisco do Pará',
  'São Geraldo do Araguaia',
  'São João da Ponta',
  'São João de Pirabas',
  'São João do Araguaia',
  'São Miguel do Guamá',
  'São Sebastião da Boa Vista',
  'Sapucaia',
  'Senador José Porfírio',
  'Soure',
  'Tailândia',
  'Terra Alta',
  'Terra Santa',
  'Tomé-Açu',
  'Tracuateua',
  'Trairão',
  'Tucumã',
  'Tucuruí',
  'Ulianópolis',
  'Uruará',
  'Vigia',
  'Viseu',
  'Vitória do Xingu',
  'Xinguara',
];
  
 