import { EntrevistadoInput } from "../../../shared/types/EntrevistadoInput";

// nomes bonitinhos pra mostrar pro usuário
export const FIELD_LABEL_ENTREVISTADO: Partial<Record<keyof EntrevistadoInput, string>> = {
    nome: 'Nome',
    naturalidade: 'Naturalidade',
    nascimentoData: 'Idade',
    sexo: 'Sexo',
    apelido: 'Apelido',
    escolaridade: 'Escolaridade',
    estadoCivil: 'Estado civil',
    religiao: 'Religião',
    morador: 'Se é morador',
    dataChegada: 'Tempo que reside no local',
    pretendeMudar: 'Se pretende mudar',
    motivoVontadeMudanca: 'Motivo da mudança',
    relacaoAreaImovel: 'Relação com o local',
    relacaoVizinhos: 'Relação com a vizinhança',
    tipoAlimentacao: 'Tipo de alimentação',
    localCompras: 'Local de compras',
    comoCuidaSaudeFamilia: 'Como cuida da saúde da família',
    servicosDeficitarios: 'Serviços públicos deficitários',
    sofreuAssaltos: 'Quantidade de vezes que sofreu assalto',
    presenciouAssalto: 'Quantidade de vezes que presenciou assalto',
    problemasDeViolenciaLocal: 'Problemas de violência no local',
    instituicaoConhecida: 'Instituição conhecida',
    importanciaDeProtegerAmbiente: 'Importância de proteger o ambiente',
    importanciaDeProtegerFauna: 'Importância de proteger a fauna',
    qualEspacoPrecisaSerPreservado: 'Espaço que precisa ser preservado',
    problemasRelacionadosAoAmbiente: 'Problemas relacionados ao ambiente',
    conheceUcs: 'Se conhece UC',
    conheceUcProposta: 'Se conhece a proposta da UC',
    conheceAreaUc: 'Se conhece a área da UC',
    utilizaAreaUc: 'Se utiliza a área',
    propostaMelhorarArea: 'Proposta para melhorar a área',
    indicadoConsultaPublica: 'Indicado para consulta pública',
    contatoIndicadoConsultaPublica: 'Contato do indicado',
  };
  